spring:
  application:
    name: hotel-service

  datasource:
      url: jdbc:postgresql://localhost:5432/hotel_service
      username: admin
      password: admin
      driver-class-name: org.postgresql.Driver

  jpa:
      hibernate:
          ddl-auto: update
      properties:
          hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          format_sql: true
      show-sql: true

server:
  port: 8088

