spring:
  application:
    name: hotel-service

  config:
    import: 
      - optional:configserver:http://localhost:7777/

resilience4j:
  circuitbreaker:
    instances:
      locationService:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30000ms
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 5
