spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mahdiboughrous/rent-app-spring
          searchPaths: configs 

server:
    port: 7777 